collections_dir: collections
collections:
  #Characters
  charactersLostMinesOfPhandelver:
  charactersBastionHelpers:
  charactersBaldursGate:
  charactersRecurringCharacters:
  charactersWolfhaven:
  # Locations
  locationsMaterialPlane:
  locationsFeywild:


# Special keys used in the URL
characterUrlKey: "character-id"
locationUrlKey: "location-id"
locationTabUrlKey: "location-tab"
